# https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
_extends: .github
version-template: $MAJOR.$MINOR.$PATCH
tag-template: jackson2-ap-$NEXT_PATCH_VERSION
name-template: $NEXT_PATCH_VERSION
